### PR TITLE
Fix spelling of clan title Marshal

### PR DESCRIPTION
**Pull request by rorro**

### CODE REVIEW

**Comment by psikoi** [comment]
Probably would need to change the icon's file name too right?

**Comment by rorro** [comment]
It seems like a file with the correct name already exists.
Marshal: https://github.com/wise-old-man/wise-old-man/blob/master/app/public/img/runescape/roles/Marshal.png
Marshall: https://github.com/wise-old-man/wise-old-man/blob/master/app/public/img/runescape/roles/Marshall.png

**Comment by psikoi** [comment]
Weird, can you remove the unused one, then?

**Comment by rorro** [comment]
Done

**Pull request merged**
