### PR TITLE
feat: add support for GB countries

### LINKED ISSUE #1441: Add Scotland, Wales and Northern Ireland as valid countries (exception to ISO 3166-1 Alpha-2)
From:
https://discord.com/channels/679454777708380161/696219233167736884/1209898743575617556
https://discord.com/channels/679454777708380161/696219233167736884/835180973158039552
https://discord.com/channels/679454777708380161/696219233167736884/1099573137819058206
https://discord.com/channels/679454777708380161/696219233167736884/1117498297498738738

Our country codes are based on the [ISO 3166-1 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), but some countries are missing from this list because they are included in the United Kingdom (GB).

It would be alright for us to add some exceptions to this list:

- `GB-WLS`: Wales (icon: https://hatscripts.github.io/circle-flags/flags/gb-wls.svg)
- `GB-SCT`: Scotland (icon: https://hatscripts.github.io/circle-flags/flags/gb-sct.svg)
- `GB-NIR`: Northern Ireland (icon: https://hatscripts.github.io/circle-flags/flags/gb-nir.svg)

Other countries can be added in the future if there's demand for them.

# Changes required
- Add these country codes to `/server/schema.prisma`
- Add enum mappings to `/server/src/prisma/enum-adapter.ts` (it's a hack, I know, I'm sorry)
- Add these countries to `/server/src/utils/countries.ts`
- Update the error message on `/server/src/api/util/validation.ts` to mention these new exceptions.
- Check if `countryCodeEmoji` or `emojiCountryCode` need changes (on https://github.com/wise-old-man/discord-bot)
- Add those SVG icons to  `/app/public/img` with the country codes as the file name. (ex: `GB-SCT.svg`)

### PR DESCRIPTION
**Pull request by caffeinated-dev**
This feature adds Northern Ireland, Scotland and Wales to the enum of supported countries for users to represent on Wise Old Man.

Closes #1441

### CODE REVIEW

**Comment by caffeinated-dev** [comment]
Hey @psikoi, the enums are now using underscores as part of commit: 57de90fbcba33b290e6ced06e21ed0d6eebaa4f6

I'll generate the migration and resolve the conflicts today 👍

**Comment by caffeinated-dev** [comment]
Feedback actioned @psikoi, I tried bumping to .17 but there was still a conflict (obviously) - I wasn't sure if this branch should increment to .17 or .16 to be aligned with master.

**Comment by psikoi** [comment]
> Feedback actioned @psikoi, I tried bumping to .17 but there was still a conflict (obviously) - I wasn't sure if this branch should increment to .17 or .16 to be aligned with master.

Should be .17

**Comment by caffeinated-dev** [comment]
All resolved @psikoi

**Pull request merged**
